spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: cityzens
    hikari:
      driver-class-name: org.postgresql.Driver
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
server:
  port: 8081