spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: cityzens
    hikari:
      driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: shayrbekov05@gmail.com
    password: qtce zile dlqa kzym
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
server:
  port: 8081