
CREATE TABLE analysis
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id BIGINT                                  NOT NULL,
    hemoglobin INTEGER                                 NOT NULL,
    platelet   INTEGER                                 NOT NULL,
    glucose    DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_analysis PRIMARY KEY (id)
);

CREATE TABLE diagnosis
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    patient_id BIGINT,
    CONSTRAINT pk_diagnosis PRIMARY KEY (id)
);

CREATE TABLE patients
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    surname VARCHAR(255),
    email   VARCHAR(255),
    gender  VARCHAR(255),
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_email UNIQUE (email);

ALTER TABLE analysis
    ADD CONSTRAINT FK_ANALYSIS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE diagnosis
    ADD CONSTRAINT FK_DIAGNOSIS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);